### ISSUE TITLE
Class based branch(platformio) doesn't read softwareSerial 

### ISSUE THREAD

**Issue by Duckle29** [Hal9k-dk/bigbro#1]
For some odd reason, the software serial input from the RFID read always reads 0.

**Comment by jenrik** [comment]
Both led in BaseController and the cardreader softwareserial uses pin 14

**Comment by Duckle29** [comment]
Changed pin definition. The LED now works, so that's nice. This issue sadly isn't solved though :(

**Comment by Duckle29** [comment]
It seems there are some issues with interrupts not getting called in our code.

I modified the software serial library to send a quick pulse each time the ISR was run, allowing me to see if it ran as expected. The first image is from the sanity-check code at the bottom of main.cpp. This runs as expected. The ISR is called on the first falling edge, and then isn't called for the rest of that byte, as interrupts are disabled during each byte.

The two next pictures are from our code, where interrupts are very rare, and even happen when they shouldn't, and seem to happen multiple times when they do happen. The interrupts are falling_edge interrupts, so they shouldn't happen when the serial line is idling high.

![image](https://user-images.githubusercontent.com/2756925/45588371-2077b280-b914-11e8-8786-47d3dd5abf65.png)

![image](https://user-images.githubusercontent.com/2756925/45588384-4ef58d80-b914-11e8-956a-51be87966fd2.png)

![image](https://user-images.githubusercontent.com/2756925/45588392-6df41f80-b914-11e8-9c19-b450ee2554bf.png)

**Comment by Duckle29** [comment]
Also, for some reason, in our code, the serial buffer seems to be constantly filled with 0. Now, it probably initializes to 0, but the in-position pointer increments fairly rapidly, until m_serial.available() returns 63. That is, the buffer is full.

This, in turn, results in m_serial.read() returning 0, and not -1 as it should if you try to read, and no data is present.

A few ways this could happen:

1. Seeing as the ISR is triggered weirdly, there might be some IO issues, and the pin might be read as LOW, even when it's high. Perhaps, the pin is always read as low, with rare pulses to high. 
2. Somehow the in-pointer on the buffer is incremented when it shouldn't be 

I think #1 is much more likely. If #1 is the way it fails, that'd also explain how we're getting spurious falling-edge interrupts when the IO is high

**Comment by Duckle29** [comment]
https://youtu.be/sC7DmMVPMBY?t=4680 Shit breaks like this

**Comment by Duckle29** [comment]
Check bughunt branch to see the code

For some reason, interrupts don't fire in software serial, if the controller is of type ACS, derived from class base

**Comment by Duckle29** [comment]
This is what the issue looks like in the bughunt branch
![image](https://user-images.githubusercontent.com/2756925/45598226-b9700180-b9d8-11e8-9944-2533678ec5d2.png)

The problem is different here. In this case it's no interrupts at all. I have verified that the "attachInterrupt" function is called in softwareserial, so it does try to attach an interrupt, but it doesn't take effect.

**Comment by jenrik** [comment]
I have tried adding a counter to SoftwareSerial that gets incremented in SoftwareSerial::rxRead(). It's getting incremented a lot which seems to indicate that interrupts are triggered. The problem now seem to be that interrupts are triggered all the time regardless of whether the rx pin has changed state, and that the it always receives 0 on the software serial.
