### ISSUE TITLE
ESP hangs on software reboot

### ISSUE THREAD

**Issue by Duckle29** [Hal9k-dk/bigbro#3]
Using Either ESP.reset() or ESP.restart() hangs the ESP, with periodic WDT resets, that still doesn't properly reset it.

However a power-cycle or a push of the reset button works as expected

**Comment by larsch** [comment]
Perhaps: https://arduino-esp8266.readthedocs.io/en/2.4.2/faq/readme.html#i-have-observed-a-case-when-esp-restart-doesn-t-work-what-is-the-reason-for-that

**Comment by Duckle29** [comment]
Yep that's it
