### ISSUE TITLE
Display shows last user who swiped their card, not the actual last user

### ISSUE THREAD

**Issue by bullestock** [Hal9k-dk/bigbro#6]
Simply inserting a card erases any information about the last user who printed.

Probably better to get the info from the backend anyway,

**Comment by Duckle29** [comment]
Is there an endpoint on the API to get the last user for the printer?

**Comment by bullestock** [comment]
> Is there an endpoint on the API to get the last user for the printer?

But of course: https://github.com/Hal9k-dk/acs/blob/master/apidoc.md

**Comment by Duckle29** [comment]
This has been implemented with EEPROM storage for now. Will open a new issue on moving this functionality server-side when I'm at a pc
